package com.mcgameskilz.RedDiamond.init;


import com.mcgameskilz.RedDiamond.block.*;
import com.mcgameskilz.RedDiamond.reference.Reference;
import cpw.mods.fml.common.registry.GameRegistry;

@GameRegistry.ObjectHolder(Reference.MOD_ID)
public class ModBlocks
{
    public static final BlockRDM redDiamondBlock = new BlockRedDiamondBlock();
    public static final BlockRDM concreteBlock = new BlockConcrete();
    public static final BlockRDM hardMetalBlock = new BlockHardMetal();
    public static final BlockRDM nukeBlock = new BlockNuke();
    public static final BlockRoads leftRoadBlock = new BlockLeftRoad();
    public static final BlockRoads rightRoadBlock = new BlockRightRoad();
    public static final BlockRoads middleRoadBlock = new BlockMiddleRoad();
    public static final BlockRoads basicRoadBlock = new BlockRoadBasic();
    public static final BlockRDM techBlock = new BlockTechBlock();
    public static final BlockRDM nukeBarrelBlock = new BlockNukeBarrel();
    public static final BlockRDM nukeWasteBlock = new BlockNukeWaste();
    public static final BlockRDM scrapBlock = new BlockScrapBlock();
    public static final BlockRDM superGlassBlock = new BlockSuperGlass();
    public static final BlockRoads plusTurnAsphaltRoadBlock = new BlockPlusTurnAsphaltRoad();
    public static final BlockRoads doubleLinedAsphaltRoadBlock = new BlockDoubleLinedAsphaltRoad();
    public static final BlockRoads doubleLinedAsphaltRoadBlock2 = new BlockDoubleLinedAsphaltRoad2();
    public static final BlockRoads basicRoadBlock2 = new BlockRoadBasic2();
    public static final BlockRoads leftRoadBlock2 = new BlockLeftRoad2();
    public static final BlockRoads linedRoadBlock = new BlockLinedRoad();
    public static final BlockRoads linedRoadBlock2 = new BlockLinedRoad2();
    public static final BlockRoads rightRoadBlock2 = new BlockRightRoad2();
    public static final BlockRoads tTurnLeftRoadBlock = new BlockTTurnLeftRoad();
    public static final BlockRoads tTurnLeftRoadBlock2 = new BlockTTurnLeftRoad2();
    public static final BlockRoads tTurnRightRoadBlock = new BlockTTurnRightRoad();
    public static final BlockRoads tTurnRightRoadBlock2 = new BlockTTurnRightRoad2();
    public static final BlockRoads turnLeftRoadBlock = new BlockTurnLeftRoad();
    public static final BlockRoads turnLeftRoadBlock2 = new BlockTurnLeftRoad2();
    public static final BlockRoads turnLeftInnerRoadBlock = new BlockTurnLeftInnerRoad();
    public static final BlockRoads turnLeftInnerRoadBlock2 = new BlockTurnLeftInnerRoad2();
    public static final BlockRoads turnLeftBasicRoadBlock = new BlockTurnLeftBasicRoad();
    public static final BlockRoads turnLeftBasicRoadBlock2 = new BlockTurnLeftBasicRoad2();
    public static final BlockRoads doubleLinedTurnLeftRoadBlock = new BlockDoubleLinedTurnLeftRoad();
    public static final BlockRoads doubleLinedTurnLeftRoadBlock2 = new BlockDoubleLinedTurnLeftRoad2();
    public static final BlockRoads turnLeftLinedRoadBlock = new BlockTurnLeftLinedRoad();
    public static final BlockRoads turnLeftLinedRoadBlock2 = new BlockTurnLeftLinedRoad2();
    public static final BlockRoads turnRightRoadBlock = new BlockTurnRightRoad();
    public static final BlockRoads turnRightRoadblock2 = new BlockTurnRightRoad2();
    public static final BlockRoads turnRightInnerRoadBlock = new BlockTurnRightInnerRoad();
    public static final BlockRoads turnRightInnerRoadBlock2 = new BlockTurnRightInnerRoad2();
    public static final BlockRoads turnRightBasicRoadBlock = new BlockTurnRightBasicRoad();
    public static final BlockRoads turnRightBasicRoadBlock2 = new BlockTurnRightBasicRoad2();
    public static final BlockRoads doubleLinedTurnRightRoadBlock = new BlockDoubleLinedTurnRightRoad();
    public static final BlockRoads doubleLinedTurnRightRoadBlock2 = new BlockDoubleLinedTurnRightRoad2();
    public static final BlockRoads linedTurnRightRoadBlock = new BlockLinedTurnRightRoad();
    public static final BlockRoads linedTurnRightRoadBlock2 = new BlockLinedTurnRightRoad2();
    public static final BlockRDM fleshBlock = new BlockFlesh();
    public static final BlockRDM dirtyStoneBlock = new BlockDirtyStone();
    public static final BlockRDM blueConcreteBlock = new BlockBlueConcrete();
    public static final BlockRDM blackConcreteBlock = new BlockBlackConcrete();
    public static final BlockRDM brownConcreteBlock = new BlockBrownConcrete();
    public static final BlockRDM cyanConcreteBlock = new BlockCyanConcrete();
    public static final BlockRDM greenConcreteBlock = new BlockGreenConcrete();
    public static final BlockRDM lightBlueConcreteBlock = new BlockLightBlueConcrete();
    public static final BlockRDM lightGrayConcreteBlock = new BlockLightGrayConcrete();
    public static final BlockRDM limeConcreteBlock = new BlockLimeConcrete();
    public static final BlockRDM magentaConcreteBlock = new BlockMagentaConcrete();
    public static final BlockRDM orangeConcreteBlock = new BlockOrangeConcrete();
    public static final BlockRDM pinkConcreteBlock = new BlockPinkConcrete();
    public static final BlockRDM purpleConcreteBlock = new BlockPurpleConcrete();
    public static final BlockRDM redConcreteBlock = new BlockRedConcrete();
    public static final BlockRDM whiteConcreteBlock = new BlockWhiteConcrete();
    public static final BlockRDM yellowConcreteBlock = new BlockYellowConcrete();
    public static final BlockRDM glitchedBlock = new BlockGlitch();
    public static final BlockRDM grayConcreteBlock = new BlockGrayConcrete();
    public static final BlockRDM rottenPlanksBlock = new BlockRottenPlanks();
    public static final BlockRDM poopBlock = new BlockPoop();
    public static final BlockRDM hardenedPoopBlock = new BlockPoopHardened();
    public static final BlockRDM rubyBlock = new BlockRuby();
    public static final BlockRDM sapphireBlock = new BlockSapphire();
    public static final BlockRDM C4Block = new BlockC4();
    public static final BlockRDM volcanicCobbleStone = new BlockVolcanicCobbleStone();
    public static final BlockRDM volcanicStone = new BlockVolcanicStone();
    public static final BlockRoads plusTurnStoneRoadBlock = new BlockPlusTurnStoneRoad();
    public static final BlockRoads basicStoneRoadBlock = new BlockBasicStoneRoad();
    public static final BlockRoads basicStoneRoadBlock2 = new BlockBasicStoneRoad2();
    public static final BlockRoads leftStoneRoadBlock = new BlockLeftStoneRoad();
    public static final BlockRoads leftStoneRoadBlock2 = new BlockLeftStoneRoad2();
    public static final BlockRoads middleStoneRoadBlock = new BlockMiddleStoneRoad();
    public static final BlockRoads rightStoneRoadBlock = new BlockRightStoneRoad();
    public static final BlockRoads rightStoneRoadBlock2 = new BlockRightStoneRoad2();
    public static final BlockRoads tTurnLeftStoneRoadBlock = new BlockTTurnLeftStoneRoad();
    public static final BlockRoads tTurnLeftStoneRoadBlock2 = new BlockTTurnLeftStoneRoad2();
    public static final BlockRoads tTurnRightStoneRoadBlock = new BlockTTurnRightStoneRoad();
    public static final BlockRoads tTurnRightStoneRoadBlock2 = new BlockTTurnRightStoneRoad2();
    public static final BlockRoads turnLeftStoneRoadBlock = new BlockTurnLeftStoneRoad();
    public static final BlockRoads turnLeftStoneRoadBlock2 = new BlockTurnLeftStoneRoad2();
    public static final BlockRoads turnRightStoneRoadBlock = new BlockTurnRightStoneRoad();
    public static final BlockRoads turnRightStoneRoadBlock2 = new BlockTurnRightStoneRoad2();
    public static final BlockRDM computerBlock = new BlockComputer();
    public static final BlockRDM computerDriveBlock = new BlockComputerDrive();
    public static final BlockRDM CPUCooler = new BlockCPUCooler();
    public static final BlockRDM barrelBlock = new BlockBarrel();
    public static final BlockRDM uraniumBlock = new BlockUranium();
    public static final BlockRDM buildingStoneBlock = new BlockBuildingStone();
    public static final BlockRDM chiseledCobblestoneBlock = new BlockChiseledCobblestone();
    public static final BlockRDM chiseledNetherBrickBlock = new BlockChiseledNetherBrick();
    public static final BlockRDM crackedSmoothStoneBlock = new BlockCrackedSmoothStone();
    public static final BlockRDM mossySmoothStoneBlock = new BlockMossySmoothStone();
    public static final BlockRDM starBlock = new BlockStar();
    public static final BlockRDM volcanicBrickBlock = new BlockVolcanicBrick();
    public static final BlockRDM spleefBlock = new BlockSpleefBlock();
    public static final BlockRDM roofStoneBlock = new BlockRoofStone();
    public static final BlockRDM roofStoneBrickBlock = new BlockRoofStoneBrick();
    public static final BlockRDM enderQuartzBlock = new BlockEnderQuartz();
    public static final BlockRDM quartsBrickBlock = new BlockQuartzBrick();
    public static final BlockRDM rubyOreBlock = new BlockRubyOre();
    public static final BlockRDM sapphireOreBlock = new BlockSapphireOre();
    public static final BlockRDM diamondBrickBlock = new BlockDiamondBrick();
    public static final BlockRDM hallCarpetBlock = new BlockHallCarpet();
    public static final BlockRDM hallFloorBlock = new BlockHallFloor();
    public static final BlockRDM woodFloorBlock = new BlockWoodFloor();


    public static void init()
    {
        GameRegistry.registerBlock(redDiamondBlock, "redDiamondBlock");
        GameRegistry.registerBlock(concreteBlock, "concreteBlock");
        GameRegistry.registerBlock(hardMetalBlock, "hardMetalBlock");
        GameRegistry.registerBlock(nukeBlock, "nukeBlock");
        GameRegistry.registerBlock(leftRoadBlock, "leftRoadBlock");
        GameRegistry.registerBlock(rightRoadBlock, "rightRoadBlock");
        GameRegistry.registerBlock(middleRoadBlock, "middleRoadBlock");
        GameRegistry.registerBlock(basicRoadBlock, "basicRoadBlock");
        GameRegistry.registerBlock(techBlock, "techBlock");
        GameRegistry.registerBlock(nukeBarrelBlock, "nukeBarrelBlock");
        GameRegistry.registerBlock(nukeWasteBlock, "nukeWasteBlock");
        GameRegistry.registerBlock(scrapBlock, "scrapBlock");
        GameRegistry.registerBlock(superGlassBlock, "superGlassBlock");
        GameRegistry.registerBlock(plusTurnAsphaltRoadBlock, "plusTurnAsphaltRoadBlock");
        GameRegistry.registerBlock(doubleLinedAsphaltRoadBlock, "doubleLinedAsphaltRoadBlock");
        GameRegistry.registerBlock(doubleLinedAsphaltRoadBlock2, "doubleLinedAsphaltRoadBlock2");
        GameRegistry.registerBlock(basicRoadBlock2, "basicRoadBlock2");
        GameRegistry.registerBlock(leftRoadBlock2, "leftRoadBlock2");
        GameRegistry.registerBlock(linedRoadBlock, "linedRoadBlock");
        GameRegistry.registerBlock(linedRoadBlock2, "linedRoadBlock2");
        GameRegistry.registerBlock(rightRoadBlock2, "rightRoadBlock2");
        GameRegistry.registerBlock(tTurnLeftRoadBlock, "tTurnLeftRoadBlock");
        GameRegistry.registerBlock(tTurnLeftRoadBlock2, "tTurnLeftRoadBlock2");
        GameRegistry.registerBlock(tTurnRightRoadBlock, "tTurnRightRoadBlock");
        GameRegistry.registerBlock(tTurnRightRoadBlock2, "tTurnRightRoadBlock2");
        GameRegistry.registerBlock(turnLeftRoadBlock, "turnLeftRoadBlock");
        GameRegistry.registerBlock(turnLeftRoadBlock2, "turnLeftRoadBlock2");
        GameRegistry.registerBlock(turnLeftInnerRoadBlock, "turnLeftInnerRoadBlock");
        GameRegistry.registerBlock(turnLeftInnerRoadBlock2, "turnLeftInnerRoadBlock2");
        GameRegistry.registerBlock(turnLeftBasicRoadBlock, "turnLeftBasicRoadBlock");
        GameRegistry.registerBlock(turnLeftBasicRoadBlock2, "turnLeftBasicRoadBlock2");
        GameRegistry.registerBlock(doubleLinedTurnLeftRoadBlock, "doubleLinedTurnLeftRoadBlock");
        GameRegistry.registerBlock(doubleLinedTurnLeftRoadBlock2, "doubleLinedTurnLeftRoadBlock2");
        GameRegistry.registerBlock(turnLeftLinedRoadBlock, "turnLeftLinedRoadBlock");
        GameRegistry.registerBlock(turnLeftLinedRoadBlock2, "turnLeftLinedRoadBlock2");
        GameRegistry.registerBlock(turnRightRoadBlock, "turnRightRoadBlock");
        GameRegistry.registerBlock(turnRightRoadblock2, "turnRightRoadBlock2");
        GameRegistry.registerBlock(turnRightInnerRoadBlock, "turnRightInnerRoadBlock");
        GameRegistry.registerBlock(turnRightInnerRoadBlock2, "turnRightInnerRoadBlock2");
        GameRegistry.registerBlock(turnRightBasicRoadBlock, "turnRightBasicRoadBlock");
        GameRegistry.registerBlock(turnRightBasicRoadBlock2, "turnRightBasicRoadBlock2");
        GameRegistry.registerBlock(doubleLinedTurnRightRoadBlock, "doubleLinedTurnRightRoadBlock");
        GameRegistry.registerBlock(doubleLinedTurnRightRoadBlock2, "doubleLinedTurnRightRoadBlock2");
        GameRegistry.registerBlock(linedTurnRightRoadBlock, "linedTurnRightRoadBlock");
        GameRegistry.registerBlock(linedTurnRightRoadBlock2, "linedTurnRightRoadBlock2");
        GameRegistry.registerBlock(fleshBlock, "fleshBlock");
        GameRegistry.registerBlock(dirtyStoneBlock, "dirtyStoneBlock");
        GameRegistry.registerBlock(blueConcreteBlock, "blueConcreteBlock");
        GameRegistry.registerBlock(blackConcreteBlock, "blackConcreteBlock");
        GameRegistry.registerBlock(brownConcreteBlock, "brownConcreteBlock");
        GameRegistry.registerBlock(cyanConcreteBlock, "cyanConcreteBlock");
        GameRegistry.registerBlock(greenConcreteBlock, "greenConcreteBlock");
        GameRegistry.registerBlock(lightBlueConcreteBlock, "lightBlueConcreteBlock");
        GameRegistry.registerBlock(lightGrayConcreteBlock, "lightGrayConcreteBlock");
        GameRegistry.registerBlock(limeConcreteBlock, "limeConcreteBlock");
        GameRegistry.registerBlock(magentaConcreteBlock, "magentaConcreteBlock");
        GameRegistry.registerBlock(orangeConcreteBlock, "orangeConcreteBlock");
        GameRegistry.registerBlock(pinkConcreteBlock, "pinkConcreteBlock");
        GameRegistry.registerBlock(purpleConcreteBlock, "purpleConcreteBlock");
        GameRegistry.registerBlock(redConcreteBlock, "redConcreteBlock");
        GameRegistry.registerBlock(whiteConcreteBlock, "whiteConcreteBlock");
        GameRegistry.registerBlock(yellowConcreteBlock, "yellowConcreteBlock");
        GameRegistry.registerBlock(glitchedBlock, "glitchedBlock");
        GameRegistry.registerBlock(grayConcreteBlock, "grayConcreteBlock");
        GameRegistry.registerBlock(rottenPlanksBlock, "rottenPlanksBlock");
        GameRegistry.registerBlock(poopBlock, "poopBlock");
        GameRegistry.registerBlock(hardenedPoopBlock, "hardenedPoopBlock");
        GameRegistry.registerBlock(rubyBlock, "rubyBlock");
        GameRegistry.registerBlock(sapphireBlock, "sapphireBlock");
        GameRegistry.registerBlock(C4Block, "C4Block");
        GameRegistry.registerBlock(volcanicCobbleStone, "volcanicCobbleStone");
        GameRegistry.registerBlock(volcanicStone, "volcanicStone");
        GameRegistry.registerBlock(plusTurnStoneRoadBlock, "plusTurnStoneRoadBlock");
        GameRegistry.registerBlock(basicStoneRoadBlock, "basicSToneRoadBlock");
        GameRegistry.registerBlock(basicStoneRoadBlock2, "basicStoneRoadBlock2");
        GameRegistry.registerBlock(leftStoneRoadBlock, "leftStoneRoadBlock");
        GameRegistry.registerBlock(leftStoneRoadBlock2, "leftStoneRoadBlock2");
        GameRegistry.registerBlock(middleStoneRoadBlock, "middleStoneRoadBlock");
        GameRegistry.registerBlock(rightStoneRoadBlock, "rightStoneRoadBlock");
        GameRegistry.registerBlock(rightStoneRoadBlock2, "rightStoneRoadBlock2");
        GameRegistry.registerBlock(tTurnLeftStoneRoadBlock, "tTurnLeftStoneRoadBlock");
        GameRegistry.registerBlock(tTurnLeftStoneRoadBlock2, "tTurnLeftStoneRoadBlock2");
        GameRegistry.registerBlock(tTurnRightStoneRoadBlock, "tTurnRightStoneRoadBlock");
        GameRegistry.registerBlock(tTurnRightStoneRoadBlock2, "tTurnRightStoneRoadBlock2");
        GameRegistry.registerBlock(turnLeftStoneRoadBlock, "turnLeftStoneRoadBlock");
        GameRegistry.registerBlock(turnLeftStoneRoadBlock2, "turnLeftStoneRoadBlock2");
        GameRegistry.registerBlock(turnRightStoneRoadBlock, "turnRightStoneRoadBlock");
        GameRegistry.registerBlock(turnRightStoneRoadBlock2, "turnRightStoneRoadblock2");
        GameRegistry.registerBlock(computerBlock, "computerBlock");
        GameRegistry.registerBlock(computerDriveBlock, "computerDriveBlock");
        GameRegistry.registerBlock(CPUCooler, "CPUCooler");
        GameRegistry.registerBlock(barrelBlock, "barrelBlock");
        GameRegistry.registerBlock(uraniumBlock, "uraniumBlock");
        GameRegistry.registerBlock(buildingStoneBlock, "buildingStoneBlock");
        GameRegistry.registerBlock(chiseledCobblestoneBlock, "chiseledCobblestoneBlock");
        GameRegistry.registerBlock(chiseledNetherBrickBlock, "chiseledNetherBrickBlock");
        GameRegistry.registerBlock(crackedSmoothStoneBlock, "crackedSmoothStoneBlock");
        GameRegistry.registerBlock(mossySmoothStoneBlock, "mossySmoothStoneBlock");
        GameRegistry.registerBlock(starBlock, "starBlock");
        GameRegistry.registerBlock(volcanicBrickBlock, "volcanicBrickBlock");
        GameRegistry.registerBlock(spleefBlock, "spleefBlock");
        GameRegistry.registerBlock(roofStoneBlock, "roofStoneBlock");
        GameRegistry.registerBlock(roofStoneBrickBlock, "roofStoneBrickBlock");
        GameRegistry.registerBlock(enderQuartzBlock, "enderQuartzBlock");
        GameRegistry.registerBlock(quartsBrickBlock, "quartzBrickBlock");
        GameRegistry.registerBlock(rubyOreBlock, "rubyOreBlock");
        GameRegistry.registerBlock(sapphireOreBlock, "sapphireOreBlock");
        GameRegistry.registerBlock(diamondBrickBlock, "diamondBrickBlock");
        GameRegistry.registerBlock(hallCarpetBlock, "hallCarpetBlock");
        GameRegistry.registerBlock(hallFloorBlock, "hallFloorBlock");
        GameRegistry.registerBlock(woodFloorBlock, "woodFloorBlock");

    }
}
